(* ::Package:: *)
(* so3_leaf_confinement_sphere.wl -- showcase figure: geometric meaning of the
   so(3) dynamical-Lie-algebra (DLA) rank test used as the "emulable vs genuine"
   gate for the KCBS cascade (G7 / LeafConfinementAudit in
   certification-protocol/BlackBoxCertifier.wl; Corollary 2, the "2->3 anchor",
   in certification-protocol/PROPOSITION-O3.md).

   All four functions below (KCBSDirections, So3Axis, CascadeGenerators,
   DLADimension) are reproduced VERBATIM from BlackBox/Kernel/BlackBox.wl --
   fetched directly from source, not paraphrased -- so this script recomputes
   the project's own authoritative numbers rather than asserting them.

   The physics: KCBSDirections[] gives the 5 KCBS pentagram unit vectors.
   CascadeGenerators[] builds the 4 so(3) generators that rotate between
   consecutive stage-frames of the KCBS cascade (via MatrixLog of the
   frame-to-frame rotation). So3Axis[] is the vee map so(3) -> R^3.
   DLADimension[] is the rank of the Lie algebra generated by commutator
   closure -- this IS the DLA-rank resource-scaling criterion from the
   project's Lie-Poisson framework.

   Kernel-verified facts reproduced by this script (must print factsOK=True):
     nGenerators = 4      (one per cascade transition)
     span(axes)  = 2      (the 4 generator axes span only a 2-plane in so(3))
     dlaFull     = 3      (commutator closure of all 4 generators fills so(3))
     dlaLeaf     = 1      (a SINGLE generator's closure stays 1-dimensional)

   Geometric reading (the point of this figure): a single so(3) generator's
   flow is a rotation about a fixed axis, so its orbit on the unit 2-sphere is
   a circle -- a 1-dimensional "leaf" (red ring below). DLA=1 means the
   dynamics is confined to that leaf: classically emulable by a single-axis
   optical rotation. Once >=2 non-commuting generators are combined (the
   actual KCBS cascade, DLA=3, blue point cloud below), the Lie-algebra rank
   condition (Chow-Rashevskii-type argument) lets the orbit fill the full
   2-sphere -- no single-axis classical emulation suffices. This is exactly
   the "emulable" (dla<3) vs "genuine" (dla=3) split in LeafConfinementAudit's
   Verdict logic.

   NOTE on scope: this figure visualizes the so(3) KCBS-cascade DLA (the G7
   gate). It is NOT the su(2^n) qubit cluster-state DLA computed in
   cluster-state-realization/cct_cluster_dla.wl (a different object, generic
   exponential 4^n-1 scaling) -- the two must not be conflated. It also does
   NOT depend on any claim about "unrotated standard axes" for cct-word
   mesh blueprints; that claim was checked against the repo during this
   session and could not be substantiated, so it is deliberately not used
   here or anywhere in this module.

   Ledger: G7 (LeafConfinementAudit gate), Corollary 2 / "2->3 anchor"
   (PROPOSITION-O3.md). Run: wolframscript -file so3_leaf_confinement_sphere.wl
   -> figures/leaf_sphere_{paper,gallery}.{png,pdf}.

   POST-EXPORT FRAMING NOTE (honesty/reproducibility disclosure): the deployed
   figures/leaf_sphere_*.png assets received one additional deterministic
   whitespace-only post-process after this script's own Export -- Mathematica
   lays out PlotLabel with a large default gap above a ViewPoint-framed
   Graphics3D scene, leaving ~30-40% dead canvas. The deployed PNGs were
   re-composited (title strip + fixed 20px gap + scene strip, stacked tightly,
   raster-only, via PIL) to remove that dead space; the deployed PDFs received
   only a plain CropBox restriction (no content-stream modification). Neither
   step touches geometry, data, or color -- both are pure framing/whitespace
   trims, done outside the kernel to avoid the vector-splicing pitfalls
   documented for this session (transparency-group compositing onto a blank
   PDF page desaturated text). Re-running this .wl script reproduces the
   physics and the untrimmed figure; it will not by itself reproduce the tight
   crop. *)

(* ============ verbatim from BlackBox/Kernel/BlackBox.wl (kernel-verified before any styling) ============ *)
KCBSDirections[] := Module[{c2 = Cos[Pi/5]/(1 + Cos[Pi/5])},
   Table[{Sqrt[1 - c2] Cos[4 Pi i/5], Sqrt[1 - c2] Sin[4 Pi i/5], Sqrt[c2]}, {i, 0, 4}]];
So3Axis[m_?MatrixQ] := {m[[3, 2]], m[[1, 3]], m[[2, 1]]};
CascadeGenerators[] := Module[{vecs = KCBSDirections[], frame, sf, transitions},
   frame[a_, b_] := {a, b, Cross[a, b]};
   sf = {frame[vecs[[1]], vecs[[2]]], frame[vecs[[3]], vecs[[2]]], frame[vecs[[3]], vecs[[4]]],
     frame[vecs[[5]], vecs[[4]]], frame[vecs[[5]], vecs[[1]]]};
   transitions = Table[sf[[k + 1]] . Transpose[sf[[k]]], {k, 4}];
   MatrixLog /@ N[transitions]];
DLADimension[gens_List] := Module[{comms},
   comms = Flatten[Table[So3Axis[gens[[i]] . gens[[j]] - gens[[j]] . gens[[i]]],
      {i, Length[gens]}, {j, i + 1, Length[gens]}], 1];
   MatrixRank[Join[So3Axis /@ gens, comms], Tolerance -> 10^-8]];

(* ============ recompute + hard verification gate ============ *)
dirs = N[KCBSDirections[]];
gens = CascadeGenerators[];
axes = So3Axis /@ gens;
spanVal = MatrixRank[axes, Tolerance -> 10^-8];
dlaFull = DLADimension[gens];
dlaLeaf = DLADimension[{gens[[1]]}];
factsOK = (Length[gens] == 4) && (spanVal == 2) && (dlaFull == 3) && (dlaLeaf == 1);
If[! factsOK,
   Print["FACTS CHECK FAILED -- aborting export. nGenerators=", Length[gens],
     " span=", spanVal, " dlaFull=", dlaFull, " dlaLeaf=", dlaLeaf];
   Abort[]];

(* ============ geometry: one confined "leaf" orbit + one sphere-filling orbit ============ *)
axis1 = Normalize[axes[[1]]];
seedPt = Normalize[{0.3, 0.6, 0.74}];
leafCircle = Table[RotationMatrix[th, axis1] . seedPt, {th, 0, 2 Pi, 2 Pi/160}];

SeedRandom[20260714];
stepAngle = 0.35; genericSeed = Normalize[{0.1, 0.05, 0.994}]; walkSteps = 600;
walkChoices = RandomInteger[{1, 4}, walkSteps];
walkPts = Rest[FoldList[RotationMatrix[stepAngle, Normalize[axes[[#2]]]] . #1 &, genericSeed, walkChoices]];

(* ============ render (Paper / Gallery themes) ============ *)
leafSphereV1[theme_String] := Module[
   {t, bg, ink, sphCol, dirCol, axisCol, leafCol, genuineCol},
   t = theme;
   bg = If[t == "Paper", White, RGBColor[0.047, 0.055, 0.086]];
   ink = If[t == "Paper", GrayLevel[0.15], GrayLevel[0.94]];
   sphCol = If[t == "Paper", RGBColor[0.75, 0.80, 0.88], RGBColor[0.20, 0.30, 0.45]];
   dirCol = If[t == "Paper", RGBColor[0.85, 0.55, 0.10], RGBColor[0.98, 0.75, 0.25]];
   axisCol = If[t == "Paper", GrayLevel[0.4], GrayLevel[0.65]];
   leafCol = If[t == "Paper", RGBColor[0.80, 0.20, 0.25], RGBColor[0.95, 0.35, 0.40]];
   genuineCol = If[t == "Paper", RGBColor[0.14, 0.42, 0.72], RGBColor[0.35, 0.75, 0.98]];
   Graphics3D[{
      {Opacity[If[t == "Paper", 0.10, 0.16]], sphCol, Specularity[White, 10], Sphere[{0, 0, 0}, 1]},
      {axisCol, Opacity[0.8], Thickness[0.004], Line[{-1.35 axis1, 1.35 axis1}]},
      {dirCol, Sphere[#, 0.045] & /@ dirs},
      {leafCol, Tube[leafCircle, 0.014]},
      {genuineCol, Opacity[0.65], PointSize[0.0068], Point[walkPts]}
     },
     Boxed -> False, Axes -> False, Background -> bg, ImageSize -> 680,
     ViewPoint -> {2.3, -2.1, 1.3}, ViewAngle -> 24 Degree,
     Lighting -> If[t == "Paper", "Neutral", "ThreePoint"],
     PlotLabel -> Style[
       "Lie\[Dash]Poisson so(3) leaf confinement  \[LongDash]  KCBS cascade (G7 / Corollary 2, the \"2\[RightArrow]3 anchor\")",
       11, ink, FontFamily -> "Helvetica"]]];

sPaper = leafSphereV1["Paper"];
sGallery = leafSphereV1["Gallery"];

figDir = FileNameJoin[{DirectoryName[$InputFileName], "figures"}];
If[! DirectoryQ[figDir], CreateDirectory[figDir, CreateIntermediateDirectories -> True]];
Export[FileNameJoin[{figDir, "leaf_sphere_paper.pdf"}], sPaper];
Export[FileNameJoin[{figDir, "leaf_sphere_paper.png"}], sPaper, ImageResolution -> 180];
Export[FileNameJoin[{figDir, "leaf_sphere_gallery.pdf"}], sGallery];
Export[FileNameJoin[{figDir, "leaf_sphere_gallery.png"}], sGallery, ImageResolution -> 180];

Print["factsOK = ", factsOK, "  nGenerators=", Length[gens], " span=", spanVal,
  " dlaFull=", dlaFull, " dlaLeaf=", dlaLeaf];
Print["Wrote leaf_sphere_{paper,gallery}.{png,pdf} to ", figDir,
  "  (see header note: deployed PNG/PDF in this module have an additional documented whitespace-only crop applied)"];
